USE [BHermanos]
GO

/****** Object:  Table [dbo].[ZonColonias]    Script Date: 01/27/2015 21:54:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ZonColonias](
	[idcolonia] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](500) NULL,
	[akm2] [decimal](38, 0) NULL,
	[idestado] [int] NULL,
	[idmunicipio] [int] NULL,
	[idlocalidad] [int] NULL,
	[clavecolonia] [varchar](100) NULL,
	[Prdo_NSE] [varchar](50) NULL,
	[nse_ab] [int] NULL,
	[nse_cmas] [int] NULL,
	[nse_c] [int] NULL,
	[nse_cmenos] [int] NULL,
	[nse_dmas] [int] NULL,
	[nse_d] [int] NULL,
	[nse_e] [int] NULL,
	[pobtot] [int] NULL,
	[pobmas] [int] NULL,
	[pobfem] [int] NULL,
	[p_0a2] [int] NULL,
	[p_0a2_m] [int] NULL,
	[p_0a2_f] [int] NULL,
	[p_3ymas] [int] NULL,
	[p_3ymas_m] [int] NULL,
	[p_3ymas_f] [int] NULL,
	[p_5ymas] [int] NULL,
	[p_5ymas_m] [int] NULL,
	[p_5ymas_f] [int] NULL,
	[p_12ymas] [int] NULL,
	[p_12ymas_m] [int] NULL,
	[p_12ymas_f] [int] NULL,
	[p_15ymas] [int] NULL,
	[p_15ymas_m] [int] NULL,
	[p_15ymas_f] [int] NULL,
	[p_18ymas] [int] NULL,
	[p_18ymas_m] [int] NULL,
	[p_18ymas_f] [int] NULL,
	[p_3a5] [int] NULL,
	[p_3a5_m] [int] NULL,
	[p_3a5_f] [int] NULL,
	[p_6a11] [int] NULL,
	[p_6a11_m] [int] NULL,
	[p_6a11_f] [int] NULL,
	[p_8a14] [int] NULL,
	[p_8a14_m] [int] NULL,
	[p_8a14_f] [int] NULL,
	[p_12a14] [int] NULL,
	[p_12a14_m] [int] NULL,
	[p_12a14_f] [int] NULL,
	[p_15a17] [int] NULL,
	[p_15a17_m] [int] NULL,
	[p_15a17_f] [int] NULL,
	[p_18a24] [int] NULL,
	[p_18a24_m] [int] NULL,
	[p_18a24_f] [int] NULL,
	[p_15a49_f] [int] NULL,
	[p_60ymas] [int] NULL,
	[p_60ymas_m] [int] NULL,
	[p_60ymas_f] [int] NULL,
	[rel_h_m] [decimal](38, 0) NULL,
	[pob0_14] [int] NULL,
	[pob15_64] [int] NULL,
	[pob65_mas] [int] NULL,
	[prom_hnv] [decimal](38, 0) NULL,
	[pnacent] [int] NULL,
	[pnacent_m] [int] NULL,
	[pnacent_f] [int] NULL,
	[pnacoe] [int] NULL,
	[pnacoe_m] [int] NULL,
	[pnacoe_f] [int] NULL,
	[pres2005] [int] NULL,
	[pres2005_m] [int] NULL,
	[pres2005_f] [int] NULL,
	[presoe05] [int] NULL,
	[presoe05_m] [int] NULL,
	[presoe05_f] [int] NULL,
	[p3ym_hli] [int] NULL,
	[p3ym_hli_m] [int] NULL,
	[p3ym_hli_f] [int] NULL,
	[p3hlinhe] [int] NULL,
	[p3hlinhe_m] [int] NULL,
	[p3hlinhe_f] [int] NULL,
	[p3hli_he] [int] NULL,
	[p3hli_he_m] [int] NULL,
	[p3hli_he_f] [int] NULL,
	[p5_hli] [int] NULL,
	[p5_hli_nhe] [int] NULL,
	[p5_hli_he] [int] NULL,
	[phog_ind] [int] NULL,
	[pcon_lim] [int] NULL,
	[pclim_mot] [int] NULL,
	[pclim_vis] [int] NULL,
	[pclim_leng] [int] NULL,
	[pclim_aud] [int] NULL,
	[pclim_mot2] [int] NULL,
	[pclim_men] [int] NULL,
	[pclim_men2] [int] NULL,
	[psin_lim] [int] NULL,
	[p3a5_noa] [int] NULL,
	[p3a5_noa_m] [int] NULL,
	[p3a5_noa_f] [int] NULL,
	[p6a11_noa] [int] NULL,
	[p6a11_noam] [int] NULL,
	[p6a11_noaf] [int] NULL,
	[p12a14noa] [int] NULL,
	[p12a14noam] [int] NULL,
	[p12a14noaf] [int] NULL,
	[p15a17a] [int] NULL,
	[p15a17a_m] [int] NULL,
	[p15a17a_f] [int] NULL,
	[p18a24a] [int] NULL,
	[p18a24a_m] [int] NULL,
	[p18a24a_f] [int] NULL,
	[p8a14an] [int] NULL,
	[p8a14an_m] [int] NULL,
	[p8a14an_f] [int] NULL,
	[p15ym_an] [int] NULL,
	[p15ym_an_m] [int] NULL,
	[p15ym_an_f] [int] NULL,
	[p15ym_se] [int] NULL,
	[p15ym_se_m] [int] NULL,
	[p15ym_se_f] [int] NULL,
	[p15pri_in] [int] NULL,
	[p15pri_inm] [int] NULL,
	[p15pri_inf] [int] NULL,
	[p15pri_co] [int] NULL,
	[p15pri_com] [int] NULL,
	[p15pri_cof] [int] NULL,
	[p15sec_in] [int] NULL,
	[p15sec_inm] [int] NULL,
	[p15sec_inf] [int] NULL,
	[p15sec_co] [int] NULL,
	[p15sec_com] [int] NULL,
	[p15sec_cof] [int] NULL,
	[p18ym_pb] [int] NULL,
	[p18ym_pb_m] [int] NULL,
	[p18ym_pb_f] [int] NULL,
	[pea] [int] NULL,
	[pea_m] [int] NULL,
	[pea_f] [int] NULL,
	[pe_inac] [int] NULL,
	[pe_inac_m] [int] NULL,
	[pe_inac_f] [int] NULL,
	[pocupada] [int] NULL,
	[pocupada_m] [int] NULL,
	[pocupada_f] [int] NULL,
	[pdesocup] [int] NULL,
	[pdesocup_m] [int] NULL,
	[pdesocup_f] [int] NULL,
	[psinder] [int] NULL,
	[pder_ss] [int] NULL,
	[pder_imss] [int] NULL,
	[pder_iste] [int] NULL,
	[pder_istee] [int] NULL,
	[pder_segp] [int] NULL,
	[p12ym_solt] [int] NULL,
	[p12ym_casa] [int] NULL,
	[p12ym_sepa] [int] NULL,
	[pcatolica] [int] NULL,
	[pncatolica] [int] NULL,
	[potras_rel] [int] NULL,
	[psin_relig] [int] NULL,
	[tothog] [int] NULL,
	[hogjef_m] [int] NULL,
	[hogjef_f] [int] NULL,
	[pobhog] [int] NULL,
	[phogjef_m] [int] NULL,
	[phogjef_f] [int] NULL,
	[vivtot] [int] NULL,
	[tvivhab] [int] NULL,
	[tvivpar] [int] NULL,
	[vivpar_hab] [int] NULL,
	[tvivparhab] [int] NULL,
	[vivpar_des] [int] NULL,
	[vivpar_ut] [int] NULL,
	[ocupvivpar] [int] NULL,
	[vph_pisodt] [int] NULL,
	[vph_pisoti] [int] NULL,
	[vph_1dor] [int] NULL,
	[vph_2ymasd] [int] NULL,
	[vph_1cuart] [int] NULL,
	[vph_2cuart] [int] NULL,
	[vph_3ymasc] [int] NULL,
	[vph_c_elec] [int] NULL,
	[vph_s_elec] [int] NULL,
	[vph_aguadv] [int] NULL,
	[vph_aguafv] [int] NULL,
	[vph_excsa] [int] NULL,
	[vph_drenaj] [int] NULL,
	[vph_nodren] [int] NULL,
	[vph_c_serv] [int] NULL,
	[vph_snbien] [int] NULL,
	[vph_radio] [int] NULL,
	[vph_tv] [int] NULL,
	[vph_refri] [int] NULL,
	[vph_lavad] [int] NULL,
	[vph_autom] [int] NULL,
	[vph_pc] [int] NULL,
	[vph_telef] [int] NULL,
	[vph_cel] [int] NULL,
	[vph_inter] [int] NULL,
	[graproes1] [decimal](38, 0) NULL,
	[graproes_m1] [decimal](38, 0) NULL,
	[graproes_f1] [decimal](38, 0) NULL,
	[prom_ocup1] [decimal](38, 0) NULL,
	[pro_ocup_c1] [decimal](38, 0) NULL,
 CONSTRAINT [PK_ZonColonias] PRIMARY KEY CLUSTERED 
(
	[idcolonia] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


